# Generated by Django 5.2.6 on 2025-10-02 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='সদস্যের নাম')),
                ('role', models.CharField(choices=[('President', 'President'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Committee', 'Committee'), ('Member', 'Member')], default='Member', max_length=50, verbose_name='পদবি')),
                ('area', models.CharField(max_length=100, verbose_name='এলাকা')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='ফোন নম্বর')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('bio', models.TextField(blank=True, verbose_name='সংক্ষিপ্ত পরিচয়')),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='ছবি')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='যোগদানের তারিখ')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'সদস্য',
                'verbose_name_plural': 'সদস্যগণ',
                'ordering': ['role', 'name'],
            },
        ),
    ]
